import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import SideNav from "./components/SideNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" className="notranslate" translate="no">
      <body>
        <nav style={{ position: 'sticky', top: 0, zIndex: 1000, background: 'rgba(15, 23, 42, 0.95)', backdropFilter: 'blur(10px)', padding: '1rem', borderBottom: '1px solid rgba(255,255,255,0.1)', display: 'flex', gap: '2rem', justifyContent: 'center', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.5)' }}>
          <a href="/" style={{ color: 'var(--text-main)', textDecoration: 'none', fontWeight: 'bold' }}>الحضور والانصراف</a>
          <a href="/employees" style={{ color: 'var(--text-main)', textDecoration: 'none', fontWeight: 'bold' }}>الموظفين</a>
          <a href="/payroll" style={{ color: 'var(--text-main)', textDecoration: 'none', fontWeight: 'bold' }}>الرواتب</a>
        </nav>
        <SideNav />
        {children}
      </body>
    </html>
  );
}
